# Generated by Django 4.1.6 on 2023-02-26 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anxiety',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ques1', models.FileField(upload_to='anxiety/')),
                ('ques2', models.FileField(upload_to='anxiety/')),
                ('ques3', models.FileField(upload_to='anxiety/')),
                ('ques4', models.FileField(upload_to='anxiety/')),
                ('ques5', models.FileField(upload_to='anxiety/')),
            ],
        ),
        migrations.CreateModel(
            name='Anxiety_Stag2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.IntegerField()),
                ('ques', models.CharField(max_length=100)),
                ('op1', models.CharField(max_length=150)),
                ('op2', models.CharField(max_length=150)),
                ('op3', models.CharField(max_length=150)),
                ('op4', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='common',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cmn', models.FileField(upload_to='uploads/')),
            ],
        ),
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=200)),
                ('phone', models.BigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='RoomMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('uid', models.CharField(max_length=200)),
                ('room_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Stress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ques1', models.FileField(upload_to='stress/')),
                ('ques2', models.FileField(upload_to='stress/')),
                ('ques3', models.FileField(upload_to='stress/')),
                ('ques4', models.FileField(upload_to='stress/')),
                ('ques5', models.FileField(upload_to='stress/')),
                ('ques6', models.FileField(upload_to='stress/')),
                ('ques7', models.FileField(upload_to='stress/')),
            ],
        ),
        migrations.CreateModel(
            name='Stress_Stag2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.IntegerField()),
                ('ques', models.CharField(max_length=100)),
                ('op1', models.CharField(max_length=100)),
                ('op2', models.CharField(max_length=100)),
                ('op3', models.CharField(max_length=100)),
                ('op4', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage0', models.CharField(max_length=2000)),
                ('stage1', models.CharField(max_length=150)),
                ('stage2', models.CharField(max_length=150)),
                ('stage3', models.CharField(max_length=150)),
                ('RoomMember', models.ManyToManyField(to='detection.roommember')),
            ],
        ),
    ]
