# Generated by Django 4.1.6 on 2023-02-27 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0002_sample_result_sample'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sample',
            name='id',
        ),
        migrations.AlterField(
            model_name='sample',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='sample',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='sample',
            name='sample_id',
            field=models.BigIntegerField(default=0, serialize=False),
        ),
    ]
