# Generated by Django 4.1.6 on 2023-02-27 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0003_remove_sample_id_alter_sample_age_alter_sample_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='email',
            field=models.EmailField(max_length=254, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sample',
            name='sample_id',
            field=models.BigIntegerField(default=0),
        ),
    ]
