# Generated by Django 4.1.6 on 2023-03-04 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0005_profile_remove_result_sample_delete_sample_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GAD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ques1', models.CharField(max_length=500)),
                ('ques2', models.CharField(max_length=500)),
                ('ques3', models.CharField(max_length=500)),
                ('ques4', models.CharField(max_length=500)),
                ('ques5', models.CharField(max_length=500)),
                ('ques6', models.CharField(max_length=500)),
                ('ques7', models.CharField(max_length=500)),
                ('res1', models.CharField(max_length=100, null=True)),
                ('res2', models.CharField(max_length=100, null=True)),
                ('res3', models.CharField(max_length=100, null=True)),
                ('res4', models.CharField(max_length=100, null=True)),
                ('res5', models.CharField(max_length=100, null=True)),
                ('res6', models.CharField(max_length=100, null=True)),
                ('res7', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
