# Generated by Django 4.1.6 on 2023-03-04 13:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('detection', '0006_gad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gad',
            name='res1',
        ),
        migrations.RemoveField(
            model_name='gad',
            name='res2',
        ),
        migrations.RemoveField(
            model_name='gad',
            name='res3',
        ),
        migrations.RemoveField(
            model_name='gad',
            name='res4',
        ),
        migrations.RemoveField(
            model_name='gad',
            name='res5',
        ),
        migrations.RemoveField(
            model_name='gad',
            name='res6',
        ),
        migrations.RemoveField(
            model_name='gad',
            name='res7',
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='DEFAULT VALUE', max_length=50)),
                ('age', models.IntegerField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('address', models.CharField(default='DEFAULT VALUE', max_length=200)),
                ('phone', models.CharField(max_length=100, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Counselor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='DEFAULT VALUE', max_length=50)),
                ('age', models.IntegerField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('address', models.CharField(default='DEFAULT VALUE', max_length=200)),
                ('phone', models.CharField(max_length=100, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
