# Generated by Django 4.1.6 on 2023-03-13 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0012_rename_ques1_acute_ques_rename_ques1_gad_ques_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acute',
            name='Profile',
        ),
        migrations.RemoveField(
            model_name='gad',
            name='Profile',
        ),
        migrations.RemoveField(
            model_name='panic',
            name='Profile',
        ),
        migrations.RemoveField(
            model_name='ptsd',
            name='Profile',
        ),
    ]
