# Generated by Django 4.1.6 on 2023-03-13 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0013_remove_acute_profile_remove_gad_profile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='counselor',
            name='address',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='address',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='address',
        ),
        migrations.AddField(
            model_name='counselor',
            name='city',
            field=models.CharField(default='null', max_length=200),
        ),
        migrations.AddField(
            model_name='counselor',
            name='date',
            field=models.CharField(default='00/00/0000', max_length=50),
        ),
        migrations.AddField(
            model_name='counselor',
            name='door',
            field=models.CharField(default='null', max_length=20),
        ),
        migrations.AddField(
            model_name='counselor',
            name='state',
            field=models.CharField(default='null', max_length=200),
        ),
        migrations.AddField(
            model_name='counselor',
            name='street',
            field=models.CharField(default='null', max_length=200),
        ),
        migrations.AddField(
            model_name='doctor',
            name='city',
            field=models.CharField(default='null', max_length=200),
        ),
        migrations.AddField(
            model_name='doctor',
            name='date',
            field=models.CharField(default='00/00/0000', max_length=50),
        ),
        migrations.AddField(
            model_name='doctor',
            name='door',
            field=models.CharField(default='null', max_length=20),
        ),
        migrations.AddField(
            model_name='doctor',
            name='state',
            field=models.CharField(default='null', max_length=200),
        ),
        migrations.AddField(
            model_name='doctor',
            name='street',
            field=models.CharField(default='null', max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='city',
            field=models.CharField(default='null', max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='date',
            field=models.CharField(default='00/00/0000', max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='door',
            field=models.CharField(default='null', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='state',
            field=models.CharField(default='null', max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='street',
            field=models.CharField(default='null', max_length=200),
        ),
    ]
