# Generated by Django 4.1.6 on 2023-03-14 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0014_remove_counselor_address_remove_doctor_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acute_ans',
            name='ques',
        ),
        migrations.RemoveField(
            model_name='gad_ans',
            name='ques',
        ),
        migrations.RemoveField(
            model_name='panic_ans',
            name='ques',
        ),
        migrations.RemoveField(
            model_name='ptsd_ans',
            name='ques',
        ),
    ]
