# Generated by Django 4.1.6 on 2023-03-15 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0017_outcome'),
    ]

    operations = [
        migrations.AddField(
            model_name='roommember',
            name='op',
            field=models.CharField(default='disoder', max_length=100),
        ),
    ]
