# Generated by Django 4.1.6 on 2023-03-15 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0018_roommember_op'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roommember',
            old_name='op',
            new_name='select',
        ),
    ]
