# Generated by Django 4.1.6 on 2023-03-16 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0019_rename_op_roommember_select'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gad',
            name='ques',
        ),
        migrations.AddField(
            model_name='gad',
            name='ques1',
            field=models.CharField(default='null', max_length=500),
        ),
        migrations.AddField(
            model_name='gad',
            name='ques2',
            field=models.CharField(default='null', max_length=500),
        ),
        migrations.AddField(
            model_name='gad',
            name='ques3',
            field=models.CharField(default='null', max_length=500),
        ),
        migrations.AddField(
            model_name='gad',
            name='ques4',
            field=models.CharField(default='null', max_length=500),
        ),
        migrations.AddField(
            model_name='gad',
            name='ques5',
            field=models.CharField(default='null', max_length=500),
        ),
        migrations.AddField(
            model_name='gad',
            name='ques6',
            field=models.CharField(default='null', max_length=500),
        ),
        migrations.AddField(
            model_name='gad',
            name='ques7',
            field=models.CharField(default='null', max_length=500),
        ),
        migrations.AlterField(
            model_name='roommember',
            name='select',
            field=models.CharField(default='disorder', max_length=100),
        ),
    ]
