# Generated by Django 4.1.6 on 2023-03-25 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0020_remove_gad_ques_gad_ques1_gad_ques2_gad_ques3_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stage0',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Greetings', models.CharField(max_length=100)),
                ('Wellbeing', models.CharField(max_length=500)),
                ('About', models.CharField(max_length=500)),
                ('Strengths', models.CharField(max_length=500)),
                ('Reason', models.CharField(max_length=500)),
                ('Therapy', models.CharField(max_length=500)),
                ('Magical_Wish', models.CharField(max_length=500)),
                ('Favourite_Food', models.CharField(max_length=500)),
                ('Friend_Characteristics', models.CharField(max_length=500)),
                ('Last_Angry', models.CharField(max_length=500)),
                ('Not_like_to_do_at_home', models.CharField(max_length=500)),
                ('Profile', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='detection.profile')),
            ],
        ),
    ]
