# Generated by Django 4.1.6 on 2023-03-25 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0021_stage0'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='latitude_range',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='doctor',
            name='longitude_range',
            field=models.FloatField(default=0.0),
        ),
    ]
