# Generated by Django 4.1.6 on 2023-03-26 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0023_rename_latitude_range_doctor_latitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor', models.CharField(default='null', max_length=100)),
                ('Profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='detection.profile')),
            ],
        ),
    ]
