# Generated by Django 4.1.6 on 2023-03-26 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0025_appoint_delete_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='appoint',
            name='date',
            field=models.CharField(default='null', max_length=100),
        ),
        migrations.AddField(
            model_name='appoint',
            name='time',
            field=models.CharField(default='null', max_length=100),
        ),
    ]
