# Generated by Django 4.1.6 on 2023-03-30 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0027_stress_stag2_ans_anxiety_stag2_ans'),
    ]

    operations = [
        migrations.CreateModel(
            name='Update_Appoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Profile', models.CharField(default='null', max_length=100)),
                ('doctor', models.CharField(default='null', max_length=100)),
                ('date', models.CharField(default='null', max_length=100)),
                ('time', models.CharField(default='null', max_length=100)),
                ('appoint_number', models.CharField(default='null', max_length=100)),
            ],
        ),
    ]
