# Generated by Django 4.1.6 on 2023-03-30 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0028_update_appoint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='update_appoint',
            name='appoint_number',
            field=models.CharField(default=1, max_length=100),
        ),
    ]
