# Generated by Django 4.1.6 on 2023-03-30 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0033_adjustment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='past_appoint',
            name='appoint_number',
        ),
        migrations.RemoveField(
            model_name='past_appoint',
            name='problem',
        ),
    ]
