# Generated by Django 4.1.6 on 2023-03-30 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0034_remove_past_appoint_appoint_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='past_appoint',
            name='session',
            field=models.CharField(default='1', max_length=100),
        ),
    ]
