# Generated by Django 4.1.6 on 2023-03-30 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0035_past_appoint_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='past_appoint',
            name='treatment',
            field=models.CharField(default='null', max_length=1000),
        ),
    ]
