# Generated by Django 4.1.6 on 2023-03-30 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0038_remove_treatment_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='past_appoint',
            name='session',
            field=models.CharField(default='1', max_length=100),
        ),
    ]
