# Generated by Django 4.1.6 on 2023-03-31 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0040_answers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Acute',
        ),
        migrations.RemoveField(
            model_name='acute_ans',
            name='Profile',
        ),
        migrations.RemoveField(
            model_name='adjustment',
            name='Profile',
        ),
        migrations.DeleteModel(
            name='GAD',
        ),
        migrations.RemoveField(
            model_name='gad_ans',
            name='Profile',
        ),
        migrations.DeleteModel(
            name='Panic',
        ),
        migrations.RemoveField(
            model_name='panic_ans',
            name='Profile',
        ),
        migrations.DeleteModel(
            name='PTSD',
        ),
        migrations.RemoveField(
            model_name='ptsd_ans',
            name='Profile',
        ),
        migrations.RemoveField(
            model_name='sias',
            name='Profile',
        ),
        migrations.DeleteModel(
            name='Acute_ans',
        ),
        migrations.DeleteModel(
            name='Adjustment',
        ),
        migrations.DeleteModel(
            name='GAD_ans',
        ),
        migrations.DeleteModel(
            name='Panic_ans',
        ),
        migrations.DeleteModel(
            name='PTSD_ans',
        ),
        migrations.DeleteModel(
            name='Sias',
        ),
    ]
