# Generated by Django 4.1.6 on 2023-04-01 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0041_delete_acute_remove_acute_ans_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatment',
            name='session',
            field=models.CharField(max_length=100),
        ),
    ]
