# Generated by Django 4.1.6 on 2023-04-01 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0042_alter_treatment_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatment',
            name='Profile',
            field=models.CharField(max_length=100),
        ),
    ]
