# Generated by Django 4.1.6 on 2023-04-01 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0043_alter_treatment_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatment',
            name='treat',
            field=models.CharField(max_length=1000),
        ),
    ]
