# Generated by Django 4.1.6 on 2023-04-01 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0044_alter_treatment_treat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Severity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('res', models.CharField(max_length=4)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='detection.profile')),
            ],
        ),
    ]
