# Generated by Django 4.1.6 on 2023-04-02 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0047_stageone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stageone',
            name='ques15',
        ),
        migrations.RemoveField(
            model_name='stageone',
            name='ques16',
        ),
        migrations.RemoveField(
            model_name='stageone',
            name='ques17',
        ),
        migrations.RemoveField(
            model_name='stageone',
            name='ques18',
        ),
        migrations.RemoveField(
            model_name='stageone',
            name='ques19',
        ),
        migrations.RemoveField(
            model_name='stageone',
            name='ques20',
        ),
        migrations.RemoveField(
            model_name='stageone',
            name='ques21',
        ),
        migrations.RemoveField(
            model_name='stageone',
            name='ques22',
        ),
    ]
