# Generated by Django 4.1.6 on 2023-04-02 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0048_remove_stageone_ques15_remove_stageone_ques16_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='date',
            field=models.CharField(default='00/00/0000', max_length=1000),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(default='DEFAULT VALUE', max_length=1000),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(max_length=1000, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='street',
            field=models.CharField(default='null', max_length=1000),
        ),
    ]
