# Generated by Django 4.1.6 on 2023-04-04 04:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0049_alter_profile_date_alter_profile_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Update_Appoint',
        ),
        migrations.RemoveField(
            model_name='past_appoint',
            name='Profile',
        ),
        migrations.RemoveField(
            model_name='treatment',
            name='Profile',
        ),
        migrations.AlterField(
            model_name='appoint',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='detection.doctor'),
        ),
        migrations.AlterField(
            model_name='past_appoint',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='detection.doctor'),
        ),
        migrations.AddField(
            model_name='past_appoint',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='detection.profile'),
        ),
        migrations.AddField(
            model_name='treatment',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='detection.profile'),
        ),
    ]
